# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-27 19:12
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subName', models.CharField(max_length=256)),
                ('subDesc', models.TextField()),
                ('createdOn', models.TimeField(default=datetime.datetime(2016, 9, 28, 0, 42, 59, 27000))),
                ('modifiedOn', models.TimeField(default=datetime.datetime(2016, 9, 28, 0, 42, 59, 27000))),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtopicDesc', models.TextField(blank=True, default=None)),
                ('code', models.TextField(blank=True, default=None)),
                ('image', models.ImageField(upload_to=b'')),
                ('createdOn', models.TimeField(default=datetime.datetime(2016, 9, 28, 0, 42, 59, 28000))),
                ('modifiedOn', models.TimeField(default=datetime.datetime(2016, 9, 28, 0, 42, 59, 28000))),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicName', models.CharField(default=None, max_length=256)),
                ('verified', models.BooleanField(default=False)),
                ('rating', models.IntegerField(default=0)),
                ('publish', models.BooleanField(default=False)),
                ('createdOn', models.TimeField(default=datetime.datetime(2016, 9, 28, 0, 42, 59, 27000))),
                ('modifiedOn', models.TimeField(default=datetime.datetime(2016, 9, 28, 0, 42, 59, 27000))),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dblog.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='subtopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dblog.Topic'),
        ),
    ]
