# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-27 19:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='createdOn',
            field=models.TimeField(default=datetime.datetime(2016, 9, 28, 0, 54, 1, 105000)),
        ),
        migrations.AlterField(
            model_name='subject',
            name='modifiedOn',
            field=models.TimeField(default=datetime.datetime(2016, 9, 28, 0, 54, 1, 105000)),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='createdOn',
            field=models.TimeField(default=datetime.datetime(2016, 9, 28, 0, 54, 1, 107000)),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='modifiedOn',
            field=models.TimeField(default=datetime.datetime(2016, 9, 28, 0, 54, 1, 107000)),
        ),
        migrations.AlterField(
            model_name='topic',
            name='createdOn',
            field=models.TimeField(default=datetime.datetime(2016, 9, 28, 0, 54, 1, 106000)),
        ),
        migrations.AlterField(
            model_name='topic',
            name='modifiedOn',
            field=models.TimeField(default=datetime.datetime(2016, 9, 28, 0, 54, 1, 106000)),
        ),
    ]
