# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-27 19:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dblog', '0002_auto_20160928_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtopic',
            name='code',
        ),
        migrations.RemoveField(
            model_name='subtopic',
            name='image',
        ),
        migrations.AlterField(
            model_name='subject',
            name='createdOn',
            field=models.TimeField(default=datetime.datetime(2016, 9, 28, 1, 6, 3, 897000)),
        ),
        migrations.AlterField(
            model_name='subject',
            name='modifiedOn',
            field=models.TimeField(default=datetime.datetime(2016, 9, 28, 1, 6, 3, 897000)),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='createdOn',
            field=models.TimeField(default=datetime.datetime(2016, 9, 28, 1, 6, 3, 897000)),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='modifiedOn',
            field=models.TimeField(default=datetime.datetime(2016, 9, 28, 1, 6, 3, 897000)),
        ),
        migrations.AlterField(
            model_name='topic',
            name='createdOn',
            field=models.TimeField(default=datetime.datetime(2016, 9, 28, 1, 6, 3, 897000)),
        ),
        migrations.AlterField(
            model_name='topic',
            name='modifiedOn',
            field=models.TimeField(default=datetime.datetime(2016, 9, 28, 1, 6, 3, 897000)),
        ),
    ]
