# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-28 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dblog', '0003_auto_20160928_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='createdOn',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='modifiedOn',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='createdOn',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='modifiedOn',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='topic',
            name='createdOn',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='topic',
            name='modifiedOn',
            field=models.DateTimeField(),
        ),
    ]
